[WIP] Feature/import accounts
GUI-Automation-AT12/team1-salesforce-gui pull request #28
Opened 2021-01-23 08:53 UTC by starsaminf

2021-01-23 19:23 UTC, MirkoFer-622 commented on salesforce-gui/src/main/java/org/fundacionjala/salesforce/ui/pageObjects/account/accountImportPage/ClassicImportAccountPage.java
> +    public void chooseDataStep(final String fieldEmail, final String fileName, final String option) {
This method should return another diferent Step not the same; when you click "Next" button, where are you diven to?

2021-01-23 19:25 UTC, MirkoFer-622 commented on salesforce-gui/src/main/java/org/fundacionjala/salesforce/ui/pageObjects/account/accountImportPage/bulkDataLoadJobs/BulkDataLoadJobsPage.java
> +        List<WebElement> contendList = getDriver().findElements(CONTEND_TABLE);
Please change contend for content

2021-01-23 19:30 UTC, MirkoFer-622 commented on salesforce-gui/src/main/java/org/fundacionjala/salesforce/ui/pageObjects/account/accountImportPage/bulkDataLoadJobs/BulkDataLoadJobsPage.java
> +        }
You can reduce this to only one line:   ----->     map.put(headerList.get(i).getText(), contendList.get(i).getText())

2021-01-23 19:34 UTC, MirkoFer-622 commented on salesforce-gui/src/main/java/org/fundacionjala/salesforce/ui/pageObjects/account/accountImportPage/bulkDataLoadJobs/BulkDataLoadJobsPage.java
> +    public boolean downloadedFileNotContainFalse() throws IOException, InterruptedException {
Maybe this verification is not the responsability of teh Page Object, I think that you have to create an util to handle CSV files.

And plaese, you should change all "contend" or "content", it is not a valid English word.

2021-01-23 19:35 UTC, MirkoFer-622 commented on salesforce-gui/src/main/java/org/fundacionjala/salesforce/ui/pageObjects/account/accountImportPage/bulkDataLoadJobs/BulkDataLoadJobsPage.java
> +    public List<String> accountIdList() throws IOException {
The same for this, I think it is not the responsability of the Page Object

2021-01-23 19:46 UTC, MirkoFer-622 commented on salesforce-gui/src/main/java/org/fundacionjala/salesforce/utils/CSVUtil.java
> +public final class CSVUtil {
MAybe this class should be named CSVReader

2021-01-23 19:47 UTC, MirkoFer-622 commented on salesforce-gui/src/test/java/org/fundacionjala/salesforce/cucumber/hooks/AccountHooks.java
> +            System.out.println(accountId.replace("\"", ""));
Avoid printing lines in develop code.

2021-01-23 19:48 UTC, MirkoFer-622 commented on salesforce-gui/src/test/java/org/fundacionjala/salesforce/cucumber/stepdefs/ImportAccountStep.java
> +    }
Delete this step if you are not using

2021-01-23 19:50 UTC, MirkoFer-622 requested changes
Take account of the commentaries I left, please.

2021-01-26 08:45 UTC, starsaminf commented on salesforce-gui/src/test/java/org/fundacionjala/salesforce/cucumber/hooks/AccountHooks.java
> +            System.out.println(accountId.replace("\"", ""));
Sorry

2021-01-26 08:48 UTC, starsaminf commented
@MirkoFer-622 I complete the task, could you review them please?

This PR is broken because need a PR of core

2021-01-27 00:01 UTC, MirkoFer-622 approved these changes

2021-01-27 00:27 UTC, merged