[develop] Scenario - Create an opportunity that depends of an Account
GUI-Automation-AT12/team1-salesforce-gui pull request #29
Opened 2021-01-25 05:48 UTC by MirkoFer-622

2021-01-25 23:04 UTC, starsaminf requested changes

2021-01-25 23:04 UTC, samuelloza commented on salesforce-gui/src/main/java/org/fundacionjala/salesforce/constants/URLConstants.java
> +        URL_CLASSIC.put("ACCOUNT_DETAILS", "%s");
I think it's not necessary the "_" in the name of page, because the key is a String

2021-01-25 23:04 UTC, samuelloza commented on salesforce-gui/src/main/java/org/fundacionjala/salesforce/ui/entities/Opportunity.java
> +                }
For break a cycle use break; please

2021-01-25 23:04 UTC, starsaminf commented on salesforce-gui/src/main/java/org/fundacionjala/salesforce/ui/pageObjects/opportunity/opportunitiesPage/LightningOpportunitiesPage.java
> +
Please remove blank lines.

2021-01-25 23:04 UTC, starsaminf commented on salesforce-gui/src/test/java/org/fundacionjala/salesforce/cucumber/stepdefs/OpportunitySteps.java
> +
Please remove this blank line

2021-01-26 05:21 UTC, MirkoFer-622 commented
@starsaminf I already solved your comments, could you review them please?

2021-01-26 05:22 UTC, starsaminf commented
LGTM!

2021-01-26 05:23 UTC, merged